### ISSUE TITLE
RecordsViewController

### ISSUE THREAD

**Issue by Grafeeva** [nautilusnsk/Task_6#2]
Следует вынести реализацию протоколов UITableViewDataSource, UITableViewDelegate в отдельные сущности.

**Comment by Grafeeva** [comment]
Например, сделать extension'ы к RecordsViewController, которые и будут реализовывать эти протоколы. А еще лучше -  в отдельный класс.

**Comment by ker1o** [comment]
На счет вынесения в отдельный класс, здесь не совсем понял. В смысле просто в отдельном файле эти все экстеншены прописать? А то есть один метод, который с приватной переменной работает..
