### ISSUE TITLE
ReusableCell

### ISSUE THREAD

**Issue by Grafeeva** [nautilusnsk/Task_6#3]
Заменить устаревший метод 

`func dequeueReusableCell(withIdentifier identifier: String) -> UITableViewCell?`

на

`func dequeueReusableCell(withIdentifier identifier: String, for indexPath: IndexPath) -> UITableViewCell`

**Comment by Grafeeva** [comment]
```
// I really don't know how to make this kind of initialization more beautiful
let tableViewCell: UITableViewCell = tableView.dequeueReusableCell(withIdentifier: reusableCellID) ?? UITableViewCell(style: UITableViewCellStyle.value2, reuseIdentifier: reusableCellID)
```

Вот когда исправишь - тогда и будет красиво. :)

**Comment by ker1o** [comment]
да, стало лучше )
